### ISSUE TITLE
Битая ссылка на загрузку PDF

### ISSUE THREAD

**Issue by vldmkrsh** [IvanAkulov/The-Swift-Programming-Language-RUS#1]
По ссылке из README.md на книгу в PDF Яндекс.Диск отвечает `404 Not Found`

**Comment by IvanAkulov** [comment]
Добрый вечер!
Какой у Вас номер заказа или ник на сайте?

Спасибо!

От 25 January 2017 в 11:47:35 PM, Vladimir Korshunov (notifications@github.com) написал:

По ссылке из README.md на книгу в PDF Яндекс.Диск отвечает 404 Not Found

**Comment by vldmkrsh** [comment]
Я не зарегистрирован на http://swiftbook.ru. В README.md не было ничего сказано про регистрацию.

**Comment by IvanAkulov** [comment]
Книга бесплатно доступна онлайн, либо скачать можно в формате epub за 150 руб. Сейчас pdf формат не доступен для скачивания, так как устарел. Ссылку сейчас уберу.

Спасибо!

От 25 January 2017 в 11:51:10 PM, Vladimir Korshunov (notifications@github.com) написал:

Я не зарегистрирован на http://swiftbook.ru. В README.md не было ничего сказано про регистрацию.

**Comment by vldmkrsh** [comment]
Ссылка удалена в коммите c4d6ecb8ba59e379c57ce26afa8b03b52d15d25c
